name: Lint, TypeScript Check, and Format

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest # host's operating system
    steps: # each job consists of 1+ steps
      - name: Checkout commit # download the code from triggering commit
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Lint and fix
        run: npm run lint:fix
        env:
          TURSO_DB_URL: ${{secrets.TURSO_DB_URL}}
          TURSO_DB_AUTH_TOKEN: ${{secrets.TURSO_DB_AUTH_TOKEN}}
          OPEN_AI_API_KEY: ${{secrets.OPEN_AI_API_KEY}}
          SUMMARY_ENDPOINT_URL: ${{secrets.SUMMARY_ENDPOINT_URL}}
          LLAMA_API_KEY: ${{secrets.LLAMA_API_KEY}}
          AZURE_OPENAI_API_KEY: ${{secrets.AZURE_OPENAI_API_KEY}}
          AZURE_OPENAI_API_VERSION: ${{secrets.AZURE_OPENAI_API_VERSION}}
          AZURE_OPENAI_API_INSTANCE_NAME: ${{secrets.AZURE_OPENAI_API_INSTANCE_NAME}}
          AZURE_OPENAI_API_DEPLOYMENT_NAME: ${{secrets.AZURE_OPENAI_API_DEPLOYMENT_NAME}}
          LANGCHAIN_TRACING_V2: ${{secrets.LANGCHAIN_TRACING_V2}}
          PQAI_API_KEY: ${{secrets.PQAI_API_KEY}}
          ALGOLIA_WRITE_API_KEY: ${{secrets.ALGOLIA_WRITE_API_KEY}}
          NEXT_PUBLIC_ALGOLIA_APP_ID: ${{secrets.NEXT_PUBLIC_ALGOLIA_APP_ID}}
          NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY: ${{secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY}}
          NEXT_PUBLIC_ALGOLIA_INDEX_NAME: ${{secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME}}
          LANGCHAIN_ENDPOINT: ${{secrets.LANGCHAIN_ENDPOINT}}
          LANGCHAIN_API_KEY: ${{secrets.LANGCHAIN_API_KEY}}
          LANGCHAIN_PROJECT: ${{secrets.LANGCHAIN_PROJECT}}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          SENTRY_ORG: ${{secrets.SENTRY_ORG}}
          SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}
          REDIS_URL: ${{secrets.REDIS_URL}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          BUCKET_NAME: ${{secrets.BUCKET_NAME}}
          IMAGE_PREFIX_URL: ${{secrets.IMAGE_PREFIX_URL}}
          ZEPLO_TOKEN: ${{secrets.ZEPLO_TOKEN}}
          ZEPLO_SECRET: ${{secrets.ZEPLO_SECRET}}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
          CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
          NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL}}
          NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${{secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL}}
          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: ${{secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL}}
          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: ${{secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL}}

      - name: Formatting Check
        run: npm run format-check

      - name: Type check
        run: npm run type-check
